// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`renders correctly 1`] = `
<div
  className="Calculator"
>
  <div
    className="Calculator-result"
  >
    0
  </div>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    AC
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    +/-
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    %
  </button>
  <button
    className="orangeButton"
    onClick={[Function]}
    type="button"
  >
    ÷
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    7
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    8
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    9
  </button>
  <button
    className="orangeButton"
    onClick={[Function]}
    type="button"
  >
    x
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    4
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    5
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    6
  </button>
  <button
    className="orangeButton"
    onClick={[Function]}
    type="button"
  >
    -
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    1
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    2
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    3
  </button>
  <button
    className="orangeButton"
    onClick={[Function]}
    type="button"
  >
    +
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    0
  </button>
  <button
    className="whiteButton"
    onClick={[Function]}
    type="button"
  >
    .
  </button>
  <button
    className="orangeButton"
    onClick={[Function]}
    type="button"
  >
    =
  </button>
</div>
`;
